"""appointment requests

Revision ID: 1dd83da070ad
Revises: 74781dbf8d62
Create Date: 2026-08-10 23:18:02.891538

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1dd83da070ad"
down_revision: str | None = "74781dbf8d62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate does not detect enum member additions.
    op.execute("ALTER TYPE workflow_type ADD VALUE IF NOT EXISTS 'APPOINTMENT_REQUEST'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointment_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_index(
        op.f("ix_appointment_requests_patient_id"),
        "appointment_requests",
        ["patient_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_appointment_requests_patient_id"), table_name="appointment_requests")
    op.drop_table("appointment_requests")
    # ### end Alembic commands ###
