"""claims and eligibility

Revision ID: 1fd82bbb973b
Revises: 840af87195a6
Create Date: 2026-08-10 19:28:46.644698

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1fd82bbb973b"
down_revision: str | None = "840af87195a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate does not detect enum member additions.
    op.execute("ALTER TYPE workflow_type ADD VALUE IF NOT EXISTS 'CLAIM'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eligibility_checks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.String(length=100), nullable=False),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("plan_name", sa.String(length=200), nullable=False),
        sa.Column("adapter", sa.String(length=50), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("checked_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["checked_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("submitted_by", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("eligibility_check_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.String(length=100), nullable=False),
        sa.Column("plan_name", sa.String(length=200), nullable=False),
        sa.Column("denial_reason", sa.String(length=500), nullable=True),
        sa.Column("resubmit_note", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["eligibility_check_id"],
            ["eligibility_checks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_index(
        "ix_claims_org_created", "claims", ["organization_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_claims_submitted_by"), "claims", ["submitted_by"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_claims_submitted_by"), table_name="claims")
    op.drop_index("ix_claims_org_created", table_name="claims")
    op.drop_table("claims")
    op.drop_table("eligibility_checks")
    # ### end Alembic commands ###
