"""referrals and guardian portal

Revision ID: 6245b76ab2c3
Revises: 0a19fa7b0620
Create Date: 2026-08-10 19:15:04.920914

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6245b76ab2c3"
down_revision: str | None = "0a19fa7b0620"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guardian_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("guardian_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["guardian_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guardian_id", "patient_id", name="uq_guardian_patient"),
    )
    op.create_index(
        op.f("ix_guardian_links_guardian_id"), "guardian_links", ["guardian_id"], unique=False
    )
    op.create_index(
        op.f("ix_guardian_links_patient_id"), "guardian_links", ["patient_id"], unique=False
    )
    op.create_table(
        "guardian_notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("guardian_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["guardian_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_guardian_notifications_guardian",
        "guardian_notifications",
        ["guardian_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "guardian_updates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_guardian_updates_patient",
        "guardian_updates",
        ["patient_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "referrals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("submitted_by", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("concern", sa.Text(), nullable=False),
        sa.Column("consent_confirmed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_index(
        "ix_referrals_org_created", "referrals", ["organization_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_referrals_submitted_by"), "referrals", ["submitted_by"], unique=False)
    op.drop_index(
        op.f("ix_document_chunks_embedding"),
        table_name="document_chunks",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_document_chunks_embedding"),
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    op.drop_index(op.f("ix_referrals_submitted_by"), table_name="referrals")
    op.drop_index("ix_referrals_org_created", table_name="referrals")
    op.drop_table("referrals")
    op.drop_index("ix_guardian_updates_patient", table_name="guardian_updates")
    op.drop_table("guardian_updates")
    op.drop_index("ix_guardian_notifications_guardian", table_name="guardian_notifications")
    op.drop_table("guardian_notifications")
    op.drop_index(op.f("ix_guardian_links_patient_id"), table_name="guardian_links")
    op.drop_index(op.f("ix_guardian_links_guardian_id"), table_name="guardian_links")
    op.drop_table("guardian_links")
    # ### end Alembic commands ###
