"""ai request tool calls

Revision ID: 74781dbf8d62
Revises: 988a3b6bf521
Create Date: 2026-08-10 23:15:28.579702

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "74781dbf8d62"
down_revision: str | None = "988a3b6bf521"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so existing audit rows read as "no tool calls".
    op.add_column(
        "ai_requests",
        sa.Column(
            "tool_calls",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_requests", "tool_calls")
    # ### end Alembic commands ###
