"""message ai provenance

Revision ID: 7af8902c8905
Revises: 20e15ec02c23
Create Date: 2026-08-10 18:27:38.057476

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7af8902c8905"
down_revision: str | None = "20e15ec02c23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("ai_request_id", sa.UUID(), nullable=True))
    op.add_column("messages", sa.Column("simulated", sa.Boolean(), nullable=True))
    op.create_foreign_key(None, "messages", "ai_requests", ["ai_request_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_column("messages", "simulated")
    op.drop_column("messages", "ai_request_id")
    # ### end Alembic commands ###
