"""chunk embedding provider

Revision ID: 8b6cb465d1ab
Revises: 1dd83da070ad
Create Date: 2026-08-10 23:40:42.977603

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8b6cb465d1ab"
down_revision: str | None = "1dd83da070ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column(
            "embedding_provider",
            sa.String(length=50),
            nullable=False,
            server_default="local-lexical-v1",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "embedding_provider")
    # ### end Alembic commands ###
