"""risk signals reviews and workflows

Revision ID: de7fe2fdc2ca
Revises: 7af8902c8905
Create Date: 2026-08-10 18:37:53.021398

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "de7fe2fdc2ca"
down_revision: str | None = "7af8902c8905"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_instances",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "workflow_type", sa.Enum("RISK_ESCALATION", name="workflow_type"), nullable=False
        ),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workflow_instances_org_state",
        "workflow_instances",
        ["organization_id", "state"],
        unique=False,
    )
    op.create_table(
        "workflow_transitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("from_state", sa.String(length=50), nullable=True),
        sa.Column("to_state", sa.String(length=50), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workflow_transitions_workflow",
        "workflow_transitions",
        ["workflow_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "risk_signals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("NONE", "LOW_MOOD", "ANXIETY", "SELF_HARM", "CRISIS", name="risk_category"),
            nullable=False,
        ),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.Integer(), nullable=False),
        sa.Column("ai_request_id", sa.UUID(), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_request_id"],
            ["ai_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_risk_signals_org_created",
        "risk_signals",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_signals_patient_id"), "risk_signals", ["patient_id"], unique=False
    )
    op.create_table(
        "risk_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("risk_signal_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column(
            "decision", sa.Enum("ACCEPT", "EDIT", "REJECT", name="review_decision"), nullable=False
        ),
        sa.Column("severity_override", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_signal_id"],
            ["risk_signals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("risk_signal_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_reviews")
    op.drop_index(op.f("ix_risk_signals_patient_id"), table_name="risk_signals")
    op.drop_index("ix_risk_signals_org_created", table_name="risk_signals")
    op.drop_table("risk_signals")
    op.drop_index("ix_workflow_transitions_workflow", table_name="workflow_transitions")
    op.drop_table("workflow_transitions")
    op.drop_index("ix_workflow_instances_org_state", table_name="workflow_instances")
    op.drop_table("workflow_instances")
    sa.Enum(name="risk_category").drop(op.get_bind())
    sa.Enum(name="review_decision").drop(op.get_bind())
    sa.Enum(name="workflow_type").drop(op.get_bind())
    # ### end Alembic commands ###
