/**
 * API client. Types come from the generated OpenAPI schema (api-schema.d.ts,
 * regenerated by scripts/gen-api-types.sh), never written by hand.
 */

import type { components } from "./api-schema";
import { clearTokens, getAccessToken, getRefreshToken, storeTokens } from "./auth";

export type TokenPair = components["schemas"]["TokenPairResponse"];
export type Me = components["schemas"]["MeResponse"];
export type Conversation = components["schemas"]["ConversationResponse"];
export type Message = components["schemas"]["MessageResponse"];
export type ReviewItem = components["schemas"]["ReviewQueueItemResponse"];
export type ReviewDecision = components["schemas"]["ReviewDecision"];
export type OpsWorkflow = components["schemas"]["OpsWorkflowResponse"];
export type OpsWorkflowDetail = components["schemas"]["OpsWorkflowDetailResponse"];
export type OpsAIRequest = components["schemas"]["OpsAIRequestResponse"];
export type OpsAIRequestDetail = components["schemas"]["OpsAIRequestDetailResponse"];
export type OpsEvent = components["schemas"]["OpsEventResponse"];
export type OpsDlq = components["schemas"]["OpsDlqResponse"];
export type KnowledgeDocument = components["schemas"]["KnowledgeDocumentResponse"];
export type KnowledgeAnswer = components["schemas"]["AskResponse"];
export type RosterEntry = components["schemas"]["RosterEntryResponse"];
export type EligibilityResult = components["schemas"]["EligibilityResponse"];
export type Claim = components["schemas"]["ClaimResponse"];
export type ClaimTransition = components["schemas"]["OpsTransitionResponse"];
export type Referral = components["schemas"]["ReferralResponse"];
export type GuardianOverview = components["schemas"]["GuardianOverviewResponse"];

const BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export class ApiError extends Error {
  constructor(
    public status: number,
    public title: string,
    detail: string,
  ) {
    super(detail);
  }
}

async function parseProblem(response: Response): Promise<ApiError> {
  try {
    const body = await response.json();
    return new ApiError(response.status, body.title ?? "Error", body.detail ?? "");
  } catch {
    return new ApiError(response.status, "Error", response.statusText);
  }
}

async function tryRefresh(): Promise<boolean> {
  const refresh = getRefreshToken();
  if (!refresh) return false;
  const response = await fetch(`${BASE_URL}/api/v1/auth/refresh`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ refresh_token: refresh }),
  });
  if (!response.ok) {
    clearTokens();
    return false;
  }
  const pair: TokenPair = await response.json();
  storeTokens(pair.access_token, pair.refresh_token);
  return true;
}

async function request<T>(
  path: string,
  init: RequestInit = {},
  retryOn401 = true,
): Promise<T> {
  const token = getAccessToken();
  const response = await fetch(`${BASE_URL}${path}`, {
    ...init,
    headers: {
      "content-type": "application/json",
      ...(token ? { authorization: `Bearer ${token}` } : {}),
      ...init.headers,
    },
  });
  if (response.status === 401 && retryOn401 && (await tryRefresh())) {
    return request<T>(path, init, false);
  }
  if (!response.ok) throw await parseProblem(response);
  if (response.status === 204) return undefined as T;
  return response.json();
}

export async function login(email: string, password: string): Promise<TokenPair> {
  const pair = await request<TokenPair>(
    "/api/v1/auth/login",
    { method: "POST", body: JSON.stringify({ email, password }) },
    false,
  );
  storeTokens(pair.access_token, pair.refresh_token);
  return pair;
}

export const getMe = () => request<Me>("/api/v1/auth/me");

export const listConversations = () =>
  request<Conversation[]>("/api/v1/conversations");

export const createConversation = (title: string) =>
  request<Conversation>("/api/v1/conversations", {
    method: "POST",
    body: JSON.stringify({ title }),
  });

export const listMessages = (conversationId: string) =>
  request<Message[]>(`/api/v1/conversations/${conversationId}/messages?limit=100`);

export const listReviews = () => request<ReviewItem[]>("/api/v1/reviews");

export const opsListWorkflows = () => request<OpsWorkflow[]>("/api/v1/ops/workflows");

export const opsWorkflowDetail = (id: string) =>
  request<OpsWorkflowDetail>(`/api/v1/ops/workflows/${id}`);

export const opsListAIRequests = () =>
  request<OpsAIRequest[]>("/api/v1/ops/ai-requests");

export const opsAIRequestDetail = (id: string) =>
  request<OpsAIRequestDetail>(`/api/v1/ops/ai-requests/${id}`);

export const opsListEvents = () => request<OpsEvent[]>("/api/v1/ops/events");

export const opsRepublishEvent = async (id: string): Promise<void> => {
  await request<unknown>(`/api/v1/ops/events/${id}/republish`, { method: "POST" });
};

export const opsViewDlq = () => request<OpsDlq>("/api/v1/ops/dlq");

export const listKnowledgeDocuments = () =>
  request<KnowledgeDocument[]>("/api/v1/knowledge/documents");

export const checkEligibility = (memberId: string) =>
  request<EligibilityResult>("/api/v1/claims/eligibility", {
    method: "POST",
    body: JSON.stringify({ member_id: memberId }),
  });

export const listClaims = () => request<Claim[]>("/api/v1/claims");

export const submitClaim = (
  patientId: string,
  description: string,
  amountCents: number,
  eligibilityCheckId: string,
) =>
  request<Claim>("/api/v1/claims", {
    method: "POST",
    body: JSON.stringify({
      patient_id: patientId,
      description,
      amount_cents: amountCents,
      eligibility_check_id: eligibilityCheckId,
    }),
  });

export const claimHistory = (claimId: string) =>
  request<ClaimTransition[]>(`/api/v1/claims/${claimId}/history`);

export const decideClaim = (claimId: string, approve: boolean, denialReason?: string) =>
  request<{ claim_id: string; state: string }>(`/api/v1/claims/${claimId}/decision`, {
    method: "POST",
    body: JSON.stringify({ approve, denial_reason: denialReason ?? null }),
  });

export const resubmitClaim = (claimId: string, note: string) =>
  request<{ claim_id: string; state: string }>(`/api/v1/claims/${claimId}/resubmit`, {
    method: "POST",
    body: JSON.stringify({ note }),
  });

export const schoolRoster = () => request<RosterEntry[]>("/api/v1/school/roster");

export const schoolReferrals = () => request<Referral[]>("/api/v1/school/referrals");

export const submitReferral = (patientId: string, concern: string, consent: boolean) =>
  request<Referral>("/api/v1/school/referrals", {
    method: "POST",
    body: JSON.stringify({
      patient_id: patientId,
      concern,
      consent_confirmed: consent,
    }),
  });

export const pendingReferrals = () => request<Referral[]>("/api/v1/referrals");

export const decideReferral = (referralId: string, accept: boolean) =>
  request<{ referral_id: string; state: string }>(
    `/api/v1/referrals/${referralId}/decision`,
    { method: "POST", body: JSON.stringify({ accept }) },
  );

export const guardianOverview = () =>
  request<GuardianOverview>("/api/v1/guardian/overview");

export const myPatients = () =>
  request<{ patient_id: string; name: string }[]>("/api/v1/my-patients");

export const shareGuardianUpdate = async (
  patientId: string,
  content: string,
): Promise<void> => {
  await request<unknown>("/api/v1/guardian/updates", {
    method: "POST",
    body: JSON.stringify({ patient_id: patientId, content }),
  });
};

export const askKnowledge = (question: string) =>
  request<KnowledgeAnswer>("/api/v1/knowledge/ask", {
    method: "POST",
    body: JSON.stringify({ question }),
  });

export const decideReview = (
  workflowId: string,
  decision: ReviewDecision,
  severityOverride?: number,
  note?: string,
) =>
  request<{ workflow_id: string; state: string; decision: ReviewDecision }>(
    `/api/v1/reviews/${workflowId}`,
    {
      method: "POST",
      body: JSON.stringify({
        decision,
        severity_override: severityOverride ?? null,
        note: note ?? "",
      }),
    },
  );

export type StreamEvent =
  | { type: "saved"; message: Message }
  | { type: "tool"; name: string; summary: string }
  | { type: "delta"; text: string }
  | { type: "message"; message: Message }
  | { type: "error"; detail: string };

/** Streams Dira's reply over SSE, invoking onEvent per event. */
export async function streamMessage(
  conversationId: string,
  content: string,
  onEvent: (event: StreamEvent) => void,
): Promise<void> {
  const token = getAccessToken();
  const response = await fetch(
    `${BASE_URL}/api/v1/conversations/${conversationId}/messages/stream`,
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        ...(token ? { authorization: `Bearer ${token}` } : {}),
      },
      body: JSON.stringify({ content }),
    },
  );
  if (!response.ok || !response.body) throw await parseProblem(response);
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() ?? "";
    for (const line of lines) {
      if (line.startsWith("data: ")) {
        onEvent(JSON.parse(line.slice(6)) as StreamEvent);
      }
    }
  }
}

export const listAppointments = () =>
  request<
    { request_id: string; patient_name: string; note: string; created_at: string }[]
  >("/api/v1/appointments");

export const acknowledgeAppointment = (requestId: string) =>
  request<{ request_id: string; state: string }>(
    `/api/v1/appointments/${requestId}/acknowledge`,
    { method: "POST" },
  );

export const postMessage = (conversationId: string, content: string) =>
  request<Message>(`/api/v1/conversations/${conversationId}/messages`, {
    method: "POST",
    body: JSON.stringify({ content }),
  });
