/**
 * API client. Types come from the generated OpenAPI schema (api-schema.d.ts,
 * regenerated by scripts/gen-api-types.sh), never written by hand.
 */

import type { components } from "./api-schema";
import { clearTokens, getAccessToken, getRefreshToken, storeTokens } from "./auth";

export type TokenPair = components["schemas"]["TokenPairResponse"];
export type Me = components["schemas"]["MeResponse"];
export type Conversation = components["schemas"]["ConversationResponse"];
export type Message = components["schemas"]["MessageResponse"];

const BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export class ApiError extends Error {
  constructor(
    public status: number,
    public title: string,
    detail: string,
  ) {
    super(detail);
  }
}

async function parseProblem(response: Response): Promise<ApiError> {
  try {
    const body = await response.json();
    return new ApiError(response.status, body.title ?? "Error", body.detail ?? "");
  } catch {
    return new ApiError(response.status, "Error", response.statusText);
  }
}

async function tryRefresh(): Promise<boolean> {
  const refresh = getRefreshToken();
  if (!refresh) return false;
  const response = await fetch(`${BASE_URL}/api/v1/auth/refresh`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ refresh_token: refresh }),
  });
  if (!response.ok) {
    clearTokens();
    return false;
  }
  const pair: TokenPair = await response.json();
  storeTokens(pair.access_token, pair.refresh_token);
  return true;
}

async function request<T>(
  path: string,
  init: RequestInit = {},
  retryOn401 = true,
): Promise<T> {
  const token = getAccessToken();
  const response = await fetch(`${BASE_URL}${path}`, {
    ...init,
    headers: {
      "content-type": "application/json",
      ...(token ? { authorization: `Bearer ${token}` } : {}),
      ...init.headers,
    },
  });
  if (response.status === 401 && retryOn401 && (await tryRefresh())) {
    return request<T>(path, init, false);
  }
  if (!response.ok) throw await parseProblem(response);
  return response.json();
}

export async function login(email: string, password: string): Promise<TokenPair> {
  const pair = await request<TokenPair>(
    "/api/v1/auth/login",
    { method: "POST", body: JSON.stringify({ email, password }) },
    false,
  );
  storeTokens(pair.access_token, pair.refresh_token);
  return pair;
}

export const getMe = () => request<Me>("/api/v1/auth/me");

export const listConversations = () =>
  request<Conversation[]>("/api/v1/conversations");

export const createConversation = (title: string) =>
  request<Conversation>("/api/v1/conversations", {
    method: "POST",
    body: JSON.stringify({ title }),
  });

export const listMessages = (conversationId: string) =>
  request<Message[]>(`/api/v1/conversations/${conversationId}/messages?limit=100`);

export const postMessage = (conversationId: string, content: string) =>
  request<Message>(`/api/v1/conversations/${conversationId}/messages`, {
    method: "POST",
    body: JSON.stringify({ content }),
  });
