/**
 * API client. Types come from the generated OpenAPI schema (api-schema.d.ts,
 * regenerated by scripts/gen-api-types.sh), never written by hand.
 */

import type { components } from "./api-schema";
import { clearTokens, getAccessToken, getRefreshToken, storeTokens } from "./auth";

export type TokenPair = components["schemas"]["TokenPairResponse"];
export type Me = components["schemas"]["MeResponse"];
export type Conversation = components["schemas"]["ConversationResponse"];
export type Message = components["schemas"]["MessageResponse"];
export type ReviewItem = components["schemas"]["ReviewQueueItemResponse"];
export type ReviewDecision = components["schemas"]["ReviewDecision"];
export type OpsWorkflow = components["schemas"]["OpsWorkflowResponse"];
export type OpsWorkflowDetail = components["schemas"]["OpsWorkflowDetailResponse"];
export type OpsAIRequest = components["schemas"]["OpsAIRequestResponse"];
export type OpsAIRequestDetail = components["schemas"]["OpsAIRequestDetailResponse"];
export type OpsEvent = components["schemas"]["OpsEventResponse"];
export type OpsDlq = components["schemas"]["OpsDlqResponse"];
export type KnowledgeDocument = components["schemas"]["KnowledgeDocumentResponse"];
export type KnowledgeAnswer = components["schemas"]["AskResponse"];

const BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export class ApiError extends Error {
  constructor(
    public status: number,
    public title: string,
    detail: string,
  ) {
    super(detail);
  }
}

async function parseProblem(response: Response): Promise<ApiError> {
  try {
    const body = await response.json();
    return new ApiError(response.status, body.title ?? "Error", body.detail ?? "");
  } catch {
    return new ApiError(response.status, "Error", response.statusText);
  }
}

async function tryRefresh(): Promise<boolean> {
  const refresh = getRefreshToken();
  if (!refresh) return false;
  const response = await fetch(`${BASE_URL}/api/v1/auth/refresh`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ refresh_token: refresh }),
  });
  if (!response.ok) {
    clearTokens();
    return false;
  }
  const pair: TokenPair = await response.json();
  storeTokens(pair.access_token, pair.refresh_token);
  return true;
}

async function request<T>(
  path: string,
  init: RequestInit = {},
  retryOn401 = true,
): Promise<T> {
  const token = getAccessToken();
  const response = await fetch(`${BASE_URL}${path}`, {
    ...init,
    headers: {
      "content-type": "application/json",
      ...(token ? { authorization: `Bearer ${token}` } : {}),
      ...init.headers,
    },
  });
  if (response.status === 401 && retryOn401 && (await tryRefresh())) {
    return request<T>(path, init, false);
  }
  if (!response.ok) throw await parseProblem(response);
  if (response.status === 204) return undefined as T;
  return response.json();
}

export async function login(email: string, password: string): Promise<TokenPair> {
  const pair = await request<TokenPair>(
    "/api/v1/auth/login",
    { method: "POST", body: JSON.stringify({ email, password }) },
    false,
  );
  storeTokens(pair.access_token, pair.refresh_token);
  return pair;
}

export const getMe = () => request<Me>("/api/v1/auth/me");

export const listConversations = () =>
  request<Conversation[]>("/api/v1/conversations");

export const createConversation = (title: string) =>
  request<Conversation>("/api/v1/conversations", {
    method: "POST",
    body: JSON.stringify({ title }),
  });

export const listMessages = (conversationId: string) =>
  request<Message[]>(`/api/v1/conversations/${conversationId}/messages?limit=100`);

export const listReviews = () => request<ReviewItem[]>("/api/v1/reviews");

export const opsListWorkflows = () => request<OpsWorkflow[]>("/api/v1/ops/workflows");

export const opsWorkflowDetail = (id: string) =>
  request<OpsWorkflowDetail>(`/api/v1/ops/workflows/${id}`);

export const opsListAIRequests = () =>
  request<OpsAIRequest[]>("/api/v1/ops/ai-requests");

export const opsAIRequestDetail = (id: string) =>
  request<OpsAIRequestDetail>(`/api/v1/ops/ai-requests/${id}`);

export const opsListEvents = () => request<OpsEvent[]>("/api/v1/ops/events");

export const opsRepublishEvent = async (id: string): Promise<void> => {
  await request<unknown>(`/api/v1/ops/events/${id}/republish`, { method: "POST" });
};

export const opsViewDlq = () => request<OpsDlq>("/api/v1/ops/dlq");

export const listKnowledgeDocuments = () =>
  request<KnowledgeDocument[]>("/api/v1/knowledge/documents");

export const askKnowledge = (question: string) =>
  request<KnowledgeAnswer>("/api/v1/knowledge/ask", {
    method: "POST",
    body: JSON.stringify({ question }),
  });

export const decideReview = (
  workflowId: string,
  decision: ReviewDecision,
  severityOverride?: number,
  note?: string,
) =>
  request<{ workflow_id: string; state: string; decision: ReviewDecision }>(
    `/api/v1/reviews/${workflowId}`,
    {
      method: "POST",
      body: JSON.stringify({
        decision,
        severity_override: severityOverride ?? null,
        note: note ?? "",
      }),
    },
  );

export const postMessage = (conversationId: string, content: string) =>
  request<Message>(`/api/v1/conversations/${conversationId}/messages`, {
    method: "POST",
    body: JSON.stringify({ content }),
  });
